name: Run Model

on: 
  workflow_dispatch:
  push:
    branches:
      - github-action

jobs:
  compare-experiments:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    env:
      #NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
      #NEPTUNE_PROJECT_DEV: ${{ secrets.NEPTUNE_PROJECT_DEV }}
      DB_USER: ${{ secrets.CASKEY5_USERNAME }}
      DB_PWD: ${{ secrets.CASKEY5_PASSWORD }}
      DB_HOST: ${{ secrets.CASKEY5_HOST }}
      DB_DB: ${{ secrets.CASKEY5_DATABASE }}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Install requirements and run model script
        id: experiment_main
        run: |
          pip install -r requirements.txt
          python train.py

      - name: Invoke workflow in dssquad-app
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy app
          repo: Data-Science-Squad/dssquad-app
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: dm-test
