name: Retrain Model

on: [workflow_dispatch]

jobs:
  compare-experiments:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    env:
      NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
      NEPTUNE_PROJECT_DEV: ${{ secrets.NEPTUNE_PROJECT_DEV }}
      CASKEY5_USERNAME: ${{ secrets.CASKEY5_USERNAME }}
      CASKEY5_PASSWORD: ${{ secrets.CASKEY5_PASSWORD }}
      CASKEY5_HOST: ${{ secrets.CASKEY5_HOST }}

    steps:
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout dm_example_github_actions branch
        uses: actions/checkout@v2
        with:
          ref: dm_example_github_actions

      - name: Install requirements and run model script
        id: experiment_main
        run: |
          pip install -r requirements.txt
          export NEPTUNE_EXPERIMENT_TAG_ID=$(uuidgen)
          python train.py
          echo ::set-output name=experiment_tag_id::$NEPTUNE_EXPERIMENT_TAG_ID
          
      - name: Invoke workflow in dssquad-app
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy app
          repo: Data-Science-Squad/dssquad-app
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: dm-test
